services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
# параметры которые используются в тестовой среде
parameters:
#для тестрирования сервиса загрузки информации из файлов - переопределим ссылки на директории
#для работы сервиса loadDataFromFiles
# определение '%kernel.project_dir% - путь к корню проекта
# https://symfony.com/blog/new-in-symfony-3-3-a-simpler-way-to-get-the-project-root-directory
    # директория из которой загружаются файлы
    dirForLoadFiles: '%kernel.project_dir%/tests/Services/LoadReestrFromFile/dirForLoadFiles'
    # директория в которую переносятся загруженные без проблем файлы
    dirForMoveFiles: '%kernel.project_dir%/tests/Services/LoadReestrFromFile/dirForMoveFiles'
    # директория в которую переносятся файлы с ошибками валидации
    dirForMoveFilesWithError: '%kernel.project_dir%/tests/Services/LoadReestrFromFile/dirForMoveFilesWithError'
    # директория с тестовыми файлами
    dirFixturesFiles: '%kernel.project_dir%/tests/Services/LoadReestrFromFile/fixturesFiles'
    # директория для загрузки данных в таблицу ЕРПН Полученные (кредит)
    dirForFilesERPN_In: '%kernel.project_dir%/tests/Services/loadDataInFile_ERPN/In/'
    # директория для загрузки данных в таблицу ЕРПН Выданные (обязательства)
    dirForFilesERPN_Out: '%kernel.project_dir%/tests/Services/loadDataInFile_ERPN/Out/'
